# Generated by Django 5.1.6 on 2025-05-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='AdminDetails',
        ),
    ]
