# Generated by Django 5.1.6 on 2025-05-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_admin_admindetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindetails',
            name='role',
            field=models.CharField(choices=[('Accounts', 'Accounts and Finance'), ('Marketing', 'Marketing and Sales'), ('Delveloper', 'Delveloper or Technical'), ('CEO', 'Head or CEO')], default='user', max_length=10),
        ),
    ]
