# Generated by Django 5.1.6 on 2025-05-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_admindetails_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindetails',
            name='is_superAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
