# Generated by Django 5.1.6 on 2025-04-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dp',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='dp',
            name='profilepic',
            field=models.ImageField(null=True, upload_to='Profile_Pics'),
        ),
    ]
